kind: Service
apiVersion: v1

metadata:
  name: gitea-service
  namespace: {{ .Params.instanceId }}
spec:
  selector:
    app: gitea
  ports:
  - name: gitea-http
    port: 3000
    targetPort: gitea-http
  - name: gitea-ssh
    port: 2222
    targetPort: gitea-ssh