apiVersion: kudo.dev/v1beta1
parameters:
  - name: replicas
    description: Number of replicas that should be run as part of the deployment
    default: 2
  - name: instanceId
    description: instanceId of the gitea to create.
    default: gitea-id
#toggles
  - name: enable-k8s-service
    description: toggle to expose gitea as a k8s services
    default: true

  - name: enable-ingress-routes
    description: toggle to expose gitea as a k8s services
    default: false

